### ISSUE TITLE
Error report when running the main.py in OSSO

### ISSUE THREAD

**Issue by siyuankth** [MarilynKeller/OSSO#16]
Hi, 

I got this error when I try to run "python main.py  --mesh_input data/demo/body_female.ply --gender female -D -v"

"
(PY_3.8) C:\Users\Siyuanch\OSSO>python main.py  --mesh_input data/demo/body_female.ply --gender female -D -v
C:\Users\Siyuanch\anaconda3\envs\PY_3.8\lib\site-packages\chumpy\__init__.py:11: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
C:\Users\Siyuanch\anaconda3\envs\PY_3.8\lib\site-packages\chumpy\__init__.py:11: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
C:\Users\Siyuanch\anaconda3\envs\PY_3.8\lib\site-packages\chumpy\__init__.py:11: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from osso.utils.inference import infer_skeleton
  File "C:\Users\Siyuanch\OSSO\osso\utils\inference.py", line 14, in <module>
    import chumpy as ch
  File "C:\Users\Siyuanch\anaconda3\envs\PY_3.8\lib\site-packages\chumpy\__init__.py", line 11, in <module>
    from numpy import bool, int, float, complex, object, unicode, str, nan, inf
ImportError: cannot import name 'bool' from 'numpy' (C:\Users\Siyuanch\anaconda3\envs\PY_3.8\lib\site-packages\numpy\__init__.py)
"

I have no clue to solve this problem. I suspect it is because I did something wrong in the step of 'make all ' in mesh file.
1. To clarify, the mesh file itself has a subfile of mesh. I run 'make all' in the first mesh file instead of the subfile of mesh. 

![image](https://github.com/user-attachments/assets/b536e687-04e3-4702-b274-f9dd7627d0d5)

The error I got after 'make all' is shown below 
Package             Version     Editable project location
------------------- ----------- -------------------------
chumpy              0.70
colorama            0.4.6
contourpy           1.1.1
cycler              0.12.1
Cython              0.29.28
filelock            3.16.1
fonttools           4.55.2
fsspec              2024.10.0
importlib_resources 6.4.5
Jinja2              3.1.4
kiwisolver          1.4.7
MarkupSafe          2.1.5
matplotlib          3.7.5
mpmath              1.3.0
networkx            3.1
numpy               1.24.4
opencv-python       4.10.0.84
osso                0.1
packaging           24.2
pillow              10.4.0
pip                 24.3.1
PyOpenGL            3.1.7
pyparsing           3.1.4
python-dateutil     2.9.0.post0
PyYAML              6.0.2
pyzmq               26.2.0
scipy               1.10.1
setuptools          75.3.0
setuptools-scm      8.1.0
six                 1.17.0
skel                1.0         c:\users\siyuanch\skel
smplx               0.1.28
sympy               1.13.3
tomli               2.2.1
torch               2.4.1
tqdm                4.67.1
trimesh             4.5.3
typing_extensions   4.12.2
wheel               0.44.0
zipp                3.20.2

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --install-option
make: *** [Makefile:7: all] Error 2

I am not sure if it has any relationship between these two errors, but it is the most potential reason I can think of now. 

Best regards,
Siyuan

**Comment by siyuankth** [comment]
Now I upgrade the Chumpy package from 0.70 to 0.71. 
then I got error when I type 
"
python main.py  --mesh_input data/demo/body_female.ply --gender female -D -v
"
 
(PY_3.8) C:\Users\Siyuanch\OSSO>python main.py  --mesh_input data/demo/body_female.ply --gender female -D -v
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from osso.utils.inference import infer_skeleton
  File "C:\Users\Siyuanch\OSSO\osso\utils\inference.py", line 15, in <module>
    from psbody.mesh import Mesh, MeshViewer
ModuleNotFoundError: No module named 'psbody'.

I still think the error comes from the failure of 'make all' in mesh file.
![image](https://github.com/user-attachments/assets/3c4eca54-778e-48cb-bb97-7fe21a0c39c0)

Does anyone have any clue to solve this? I am using WIN10 system.

Best regards,
Siyuan

**Comment by MarilynKeller** [comment]
Are you on windows? The mesh package is only supported in Ubuntu.

**Comment by siyuankth** [comment]
Ok, it doesn't mention in the installation page. https://github.com/MarilynKeller/OSSO/blob/main/installation.md

Then it is a bit tricky, do you think can I use SKEL in my windows PC?

Best regards,
Siyuan

**Comment by siyuankth** [comment]
> Are you on windows? The mesh package is only supported in Ubuntu.

What I would like to do is to generate SKEL based on the SKIN model, I have tested 'python quickstart.py ' for SKEL, it works well, but it will output both SKIN and SKEL. Not sure how to output SKEL based on SKIN like OSSO, and hope it can be done in Windows...
